# Generated by Django 3.1 on 2020-08-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Write',
            new_name='Writer',
        ),
    ]
