# Generated by Django 3.1 on 2020-08-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.item'),
        ),
    ]
