# Generated by Django 3.1 on 2020-08-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200829_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image'),
        ),
    ]
