# Generated by Django 3.1 on 2020-09-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_itemmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemManager',
        ),
    ]
