# Generated by Django 3.1 on 2020-09-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200901_2202'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
    ]
